packageFiles = [
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\config\\pacenotes\\packages\\additional\\Extended.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\config\\pacenotes\\packages\\corners\\Numeric-Swapped.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\config\\pacenotes\\packages\\adjectives\\Extended.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\config\\pacenotes\\packages\\cautions\\Extended.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\config\\pacenotes\\packages\\condition\\Extended.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\config\\pacenotes\\packages\\construction\\Extended.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\config\\pacenotes\\packages\\driving\\Extended.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\config\\pacenotes\\packages\\line\\Extended.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\config\\pacenotes\\packages\\links\\Extended.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\config\\pacenotes\\packages\\modifier\\Extended.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\config\\pacenotes\\packages\\obstacles\\Extended.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\config\\pacenotes\\packages\\prepositions\\Extended.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\config\\pacenotes\\packages\\road\\Extended.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\config\\pacenotes\\packages\\surface\\Extended.ini",
]

stringFiles = [
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\language\\english\\pacenotes\\packages\\additional\\strings.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\language\\english\\pacenotes\\packages\\adjectives\\strings.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\language\\english\\pacenotes\\packages\\cautions\\strings.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\language\\english\\pacenotes\\packages\\condition\\strings.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\language\\english\\pacenotes\\packages\\construction\\strings.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\language\\english\\pacenotes\\packages\\corners\\strings.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\language\\english\\pacenotes\\packages\\driving\\strings.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\language\\english\\pacenotes\\packages\\line\\strings.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\language\\english\\pacenotes\\packages\\links\\strings.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\language\\english\\pacenotes\\packages\\modifier\\strings.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\language\\english\\pacenotes\\packages\\obstacles\\strings.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\language\\english\\pacenotes\\packages\\prepositions\\strings.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\language\\english\\pacenotes\\packages\\road\\strings.ini",
    R"D:\\Richard Burns Rally\\Plugins\\Pacenote\\language\\english\\pacenotes\\packages\\surface\\strings.ini",
]


for i in range(len(packageFiles)):
    thisDict = []
    file_read = open(packageFiles[i], "r")
    lines = file_read.readlines()
    for j in range(len(lines)):
        thisLine = lines[j]
        if thisLine.find("[PACENOTE::")>-1:
            thisNote = thisLine.replace("[PACENOTE::","")
            thisNote = thisNote.replace("]","")
            thisNote = thisNote.replace("\n","")
            thisRepl = thisNote
            thisRepl = thisRepl.replace("_"," ")
            thisRepl = thisRepl.replace("]","")
            thisRepl = thisRepl.replace("\n","")
            thisRepl = thisRepl.lower()
            thisDict.append(thisNote + "=" + thisRepl)
    file_write = open(stringFiles[i],"w")
    header = """;
; File:         strings.ini
; Version:      1.0
; Date:         2012-04-01
;
;
; Language:     english
; Encoding:     UTF-8
;
; We keep each section sorted to ease the tracking of changes and translation.
;
; auto generated by Wrench's python script
"""
    file_write.write(header)
    file_write.close()
    file_write = open(stringFiles[i],"a")
    for j in range(len(thisDict)):
        print(thisDict[j])
        file_write.write(str(thisDict[j]+"\n"))
    file_write.close()
